version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: kips_postgres_db
    restart: always
    environment:
      POSTGRES_USER: kips_admin
      POSTGRES_PASSWORD: db_password!
      POSTGRES_DB: kips_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
