version: '3.8'

services:

  postgres:
    image: postgres
    volumes:
      - ./docs/ddl:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products_db
      LANG: C.UTF-8
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass redisPassword
    ports:
      - "6379:6379"