eureka:
  instance:
    hostname: localhost
  client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: product-api
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/products_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non_null
  sql:
    init:
      mode: always
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 2000KB
      max-request-size: 2000KB
redis:
  password: redisPassword
  hostname: localhost
data:
  seed:
    enabled: true
server:
  port: 8081

management:
  endpoint:
    health.show-details: always
    info:
      enabled: true

file:
  download-url: http://localhost:${server.port}/api/v1/file/download
