name: SonarCloud Analysis

on:
  push:
    branches:
      - master
      - 'release/*'
  pull_request:
    branches:
      - master
      - 'release/*'

jobs:
  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - product-api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and analyze project
        working-directory: ${{ matrix.project }}
        env:
          SONAR_TOKEN: e4d8adb6d397af356a7a4ac1cc6421877b50c13c
          GITHUB_TOKEN: ${{ secrets.SONAR_GITHUB_TOKEN }}
        run: ./gradlew build sonarqube -Dsonar.login=e4d8adb6d397af356a7a4ac1cc6421877b50c13c --warning-mode all

      - name: Upload SonarCloud results
        uses: SonarSource/sonarcloud-github-action@master
        with:
          sonar-token: e4d8adb6d397af356a7a4ac1cc6421877b50c13c

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.project }}
          path: ${{ matrix.project }}/build/test-results/test
            - name: SonarCloud Scan
                uses: SonarSource/sonarcloud-github-action@master
                with:
                  args: >
                    -Dsonar.projectKey=sametakbal_kips-shop
                    -Dsonar.organization=sametakbaldeveloper
                env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
